Repository scc-digitalhub/AAC, pull requests merged in 2023-11, with the labels that each got.

#442 backport #441 to 4.x
  src/main/java/it/smartcommunitylab/aac/oauth/flow/WebhookOAuthFlowExtensions.java
Labels: backport, 4.x

#441 fix #436: register time module to object mapper for serialization
  src/main/java/it/smartcommunitylab/aac/oauth/flow/WebhookOAuthFlowExtensions.java
Labels: 5.x

#444 fix #443: added tos_configuration_map and tos_accepted columns in postgresql create table statements
  src/main/resources/db/sql/schema-postgresql.sql
Labels: 4.x

#434 test saml identity provider metadata
  src/test/java/it/smartcommunitylab/aac/saml/SamlIdentityProviderMetadataTest.java
  src/test/resources/bootstrap-test.yaml
Labels: saml, tests

#430 Test for Saml IdP Configuration
  pom.xml
  src/test/java/it/smartcommunitylab/aac/saml/SamlIdentityProviderConfigurationTest.java
Labels: saml, tests

#425 5.x.OIDC fix post endsession and authorize
  src/main/java/it/smartcommunitylab/aac/config/OAuth2UserSecurityConfig.java
  src/main/java/it/smartcommunitylab/aac/config/SecurityConfig.java
Labels: enhancement, oidc

#450 5.x bufgix tos redirect
  src/main/java/it/smartcommunitylab/aac/tos/TosOnAccessFilter.java
  src/main/java/it/smartcommunitylab/aac/tos/controller/TosController.java
Labels: 5.x
